### ISSUE TITLE
Link text which is not sufficiently clear - DAC_Non-descriptive_Links_Issue5

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/ds-wagtail#173]
On page 29 of the report DAC describe an issue with ID `DAC_Non-descriptive_Links_Issue5` which describes a number of links that are not sufficiently described. These are: 

* "Add to basket" (on multiple details pages)
* "View in the catalogue’" (on insights pages)
* "See options on how to view this document" (on insights page)

DAC have suggested we resolve this by adding the document title to the link text (for all users). It could also be achieved by using an `sr-only` class on a `<span>`.

**Comment by gtvj** [comment]
Hi @jamesbiggs - let me know if you need any support on this. We'd be happy to help 👍🏽

**Comment by JamesWChan** [comment]
Hi @piriyapordes, @MGDeVille,

I wonder if you could help with the last item in this issue ("See options on how to view this document" on the insights page). As per the DAC report, we need to make these links more descriptive:

> Ensure that all links are descriptive enough for users to easily determine their purpose and destination for users who are navigating the page both in and out of context.
Consider adding more visual link text informing users that it is the report they are adding to basket.

In the first 2 cases, James B was able to implement Gwyn's recommendation because the text is hardcoded and so we know where to put a `<span class="sr-only">`. In the case of the last item, the link text is custom and inserted by an editor in Wagtail so we'd need editors to insert something that would make the link more descriptive. Hope this makes sense; I'm happy to jump on a call to explain further if not!

**Comment by MGDeVille** [comment]
Hi @JamesWChan @piriyapordes. I reckon in this case we change it to:

**See the catalogue description for this record**

We use that elsewhere, and it fits with the prefix 'as a user I want to'. I noticed that we say the same thing a number of different ways across the four Insights, which is fine because it's good to test! But we'll probably need to standardise at some point. E.g. 

See a description of this record in our catalogue 
See the catalogue description for this record 
View in the catalogue 
See this record in our catalogue
See this record description in our catalogue
See options on how to view this document

**Comment by gtvj** [comment]
Hi @JamesWChan @MGDeVille @piriyapordes - I just wanted to check in to ask if the changes proposed by Matthew have been made?

**Comment by JamesWChan** [comment]
Hi @gtvj,

If I'm not mistaken, this needs to be done in the Wagtail editorial interface which I don't think I have access to. I don't think I'm able to code it directly because the promoted item (the component in question) is also used for things like videos and podcasts and would require the text to remain customisable.

**Comment by MGDeVille** [comment]
Hi @JamesWChan @gtvj @piriyapordes I've made those changes in Wagtail now. The changes aren't updating on live, but are saved in the back end (I hope).

**Comment by jamesbiggs** [comment]
I think we can close this issue now, it'll be stored in closed issues if it needs to be reopened for any reason.
